<a href="https://colab.research.google.com/github/almostdevelopr/data-science-python/blob/main/numpy/numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Analysis Numpy

In [1]:
import numpy as np

In [14]:
myarray=np.array([[1,2,3,4,5,6,5]])

In [5]:
myarray

array([1, 2, 3, 4, 5, 6, 5])

In [7]:
myarray.shape


(7,)

In [8]:
myarray[3]

4

In [11]:
myarray[0,2]

3

In [12]:
myarray.shape

(1, 7)

In [15]:
myarray.dtype

dtype('int64')

# Conversion from other Python structures (e.g., lists, tuples

In [17]:
list_array=np.array([[1,2,3],[3,2,1],[6,7,5]])

In [18]:
list_array

array([[1, 2, 3],
       [3, 2, 1],
       [6, 7, 5]])

In [19]:
list_array.shape

(3, 3)

In [20]:
list_array.dtype

dtype('int64')

In [21]:
list_array.size # return number of elemnts in a numpy array

9

In [22]:
dict_array=np.array({1,2,3,4,5,9})

In [23]:
dict_array

array({1, 2, 3, 4, 5, 9}, dtype=object)

# Intrinsic numpy array array creation objects (e.g., arange, ones, zeros, etc.)

In [25]:
zeros=np.zeros((2,5))

In [26]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
zeros.shape

(2, 5)

In [28]:
zeros.dtype

dtype('float64')

In [29]:
array_range=np.arange(15)

In [30]:
array_range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
array_range.dtype

dtype('int64')

In [32]:
array_range.shape

(15,)

In [37]:
# np.linspace(start_number, stop_number, number_of_numbers)
l_array=np.linspace(1,10,4)

In [38]:
l_array # return linearly spaced 4 elements between 1 to 10

array([ 1.,  4.,  7., 10.])

In [39]:
emp_array=np.empty((1,4)) # returns an empty array with random numbers number elements

In [42]:
emp_array.shape

(1, 4)

In [43]:
emp_like=np.empty_like(l_array)

In [44]:
emp_like

array([ 1.,  4.,  7., 10.])

Arange

In [45]:
range_array=np.arange(100)

Reshape

In [47]:
range_array.reshape(4,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [48]:
range_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [49]:
range_array=range_array.reshape(4,25) # reshape 1D array to given dimensions

In [50]:
range_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [51]:
range_array.shape

(4, 25)

In [52]:
range_array.dtype

dtype('int64')

In [55]:
range_array=range_array.ravel() # returns 1D array

In [56]:
range_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# Axis in numpy

In [57]:
x_list=[[1,2,3],[4,5,6],[7,1,0]]

In [59]:
type(x_list)

list

In [60]:
x_array=np.array(x_list)

In [61]:
x_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [63]:
x_array.sum(axis=0)

array([12,  8,  9])

In [64]:
x_array.sum(axis=1)

array([ 6, 15,  8])

In [66]:
# Transpose
x_array.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

array.flat returns an iterator

In [67]:
for item in x_array.T.flat:
    print(item)

1
4
7
2
5
1
3
6
0


In [68]:
some_array=np.array([1,3,22333,4,5,25,53,555555])

In [69]:
some_array.argmax() # returns index of max value in an array

7

In [70]:
some_array.argmin() # returns index of minimum value in an array

0

In [71]:
x_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [76]:
x_array.argmax()
x_array.argmin()

8

In [77]:
x_array.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [78]:
x_array.argmax(axis=0)

array([2, 1, 1])

In [79]:
x_array.argmin(axis=1)

array([0, 0, 2])

#Mathematical operations in numpy

In [80]:
arr1=x_array

In [85]:
arr2=np.arange(9)
arr2=arr2.reshape((3,3))

In [86]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [87]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [88]:
arr1+arr2

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13,  8,  8]])

In [89]:
arr1.max()

7

In [90]:
arr2.sum()

36

In [91]:
arr1*arr2

array([[ 0,  2,  6],
       [12, 20, 30],
       [42,  7,  0]])

In [92]:
# find elements
np.where(arr1>5) # returns element indices > 5

(array([1, 2]), array([2, 0]))

In [93]:
np.count_nonzero(arr1)

8

# Efficiency check for numpy

In [94]:
import sys

In [95]:
py_ar=[0,22,43,67]

In [96]:
np_ar=np.array(py_ar)

In [97]:
sys.getsizeof(1)*len(py_ar)

112

In [98]:
np_ar.itemsize*np_ar.size

32